### PR TITLE
Allow anonymous users to set filters

### LINKED ISSUE #56: allow setting filters even for non-logged in users
allow only the filters

**NOT** the schedule editing part 

image

### PR DESCRIPTION
**Pull request by kapillamba4**
Fixes #56 
image
@championswimmer

### CODE REVIEW

**Comment by bhavyaagg** [comment]
Hey @kapillamba4 , there are some issues with the PR. First of all you have removed a lot of code from public_html/index.js which was important. For example https://github.com/coding-blocks/schedulecture/blob/master/public_html/index.js#L25
These lines were there for a specific feature that is the teacher should be able to share timetable for a specific batch by query parameters. So please update your PR after resolving the conflicts.

**Comment by kapillamba4** [comment]
@bhavyaagg, updated the PR. I think this [clienttokenArray](https://github.com/coding-blocks/schedulecture/blob/master/public_html/index.js#L25) part was added after this PR. Can you review again if anything else is missing, i have resolved the conflicts

**Comment by kapillamba4** [comment]
Demo link: http://schedulecture.herokuapp.com/

**Comment by bhavyaagg** [comment]
@kapillamba4, why have you removed the following lines: https://github.com/coding-blocks/schedulecture/pull/59/files#diff-adc24b21fded9eaf1f6283bef8a8e10cL175

**Comment by kapillamba4** [comment]
@bhavyaagg I have updated the PR, review please

**Comment by bhavyaagg** [comment]
@kapillamba4 Yeah looks good to me. Can you also remove the commented code for eg in the css file.

**Pull request merged**
