### PR TITLE
Refactor backend

### PR DESCRIPTION
**Pull request by bhavyaagg**

### CODE REVIEW

**Comment by bhavyaagg** [comment]
@championswimmer Sir i have refactored the db and actions.

**Comment by championswimmer** [comment]
fix the conflicts @bhavyaagg

**Comment by bhavyaagg** [comment]
@championswimmer Sir i have resolved the conflicts here. WIll resolve for heroku one after this is merge as it will reduce the merge conflicts because both pr's has similar conflicts.

**Comment by bhavyaagg** [comment]
@championswimmer Sir i have resolved the conflicts here. WIll resolve for heroku one after this is merge as it will reduce the merge conflicts because both pr's have similar conflicts.

**Pull request merged**
