### PR TITLE
Added filters for non-logged in users

### PR DESCRIPTION
**Pull request by vibhorgupta-gh**
screen shot 2018-07-04 at 10 10 27 am

### CODE REVIEW

**Comment by championswimmer** [comment]
```
ReferenceError: eventsData is not defined
```
index.js: line : 141: char: 17

**Comment by vibhorgupta-gh** [comment]
@championswimmer made the change

**Comment by vibhorgupta-gh** [comment]
@championswimmer fixed alignments too, the filter buttons are now adjacent (as opposed to being one below the other before) and teacher names appear in a single line.

**Comment by championswimmer** [comment]
does not work. applying filters shows no classes at all.

can you please not submit untested code.

**Comment by VibhorCodecianGupta** [comment]
Apologies :(

Strange though. It was working. I'm looking into it right now.

**Comment by vibhorgupta-gh** [comment]
Apologies :(

Looking into it

**Pull request merged**
